Handle unspecified background color of default face
raxod502/profile-dotemacs pull request #3
Opened 2018-04-10 19:32 UTC by doolio

(face-background 'default) is unspecified in "no-windows" mode.This incorporates juergenhoetzel/profile-dotemacs@ff4e41cea0afd70f80d531267e492a8803d64ac3 into your repository. As with my first PR if you accept this PR please correct any errors as I'm only learning to programme.

2018-04-10 19:54 UTC, raxod502 commented
This needs to be rebased now that #2 was merged.

2018-04-11 00:29 UTC, doolio commented
My first rebase \O/ hopefully I did it right.

2018-04-11 15:39 UTC, raxod502 requested changes

2018-04-11 15:39 UTC, raxod502 commented on profile-dotemacs.el
> +>>>>>>> Handle unspecified background color of default face
You have committed merge markers. See https://stackoverflow.com/q/10657315/3538165.

2018-04-12 20:27 UTC, doolio commented
I've removed those conflict markers with a new commit. Was that the correct action or should one squash the commits into one? Thanks for your patience.

2018-04-12 23:54 UTC, raxod502 approved these changes

2018-04-12 23:54 UTC, merged

2018-04-12 23:55 UTC, raxod502 commented
It would probably make more sense to squash the commits into one. However, GitHub lets me do that while merging the pull request, so I did.

2018-04-13 09:12 UTC, doolio commented
Great, thanks.